# Generated by Django 4.2.10 on 2024-02-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('productos', models.ManyToManyField(related_name='servicios_productos', through='cotizaciones.DetalleServicio', to='cotizaciones.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='servicios',
            field=models.ManyToManyField(related_name='productos_servicios', through='cotizaciones.DetalleServicio', to='cotizaciones.servicio'),
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.producto'),
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.servicio'),
        ),
    ]
